print("##############################")
print("#                            #")
print("#    Siti Ainur Rahmawati    #")
print("#       2210817220029        #")
print("#                            #")
print("##############################")